on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create Firebase key file
        run: echo "$FIREBASE_KEY" > firebase-key.json
      
      - name: Run application
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: |
          python medapp.py
